---
name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  name: Run unit tests
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - run: go test ./...
